// <auto-generated />
using System;
using System.Text.Json;
using DMMAffiDBEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMMAffiDBEntity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMMAffiDBEntity.Entities.Master.MAffiliateUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("アフィリエイトユーザマスタID:【値例】1");

                    b.Property<string>("AIPId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("api_id")
                        .HasComment("APIID:【値例】");

                    b.Property<string>("AffiliateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("affiliate_id")
                        .HasComment("アフィリエイトID:【値例】");

                    b.Property<string>("CreateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("create_program")
                        .HasComment("作成プログラム:【値例】System");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("create_user")
                        .HasComment("作成者:【値例】System");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasComment("作成日時:【値例】2025/01/01 00:00:00");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除:【値例】false：未削除 , true：削除済み");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("update_program")
                        .HasComment("更新プログラム:【値例】System");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("update_user")
                        .HasComment("更新者:【値例】System");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date")
                        .HasComment("更新日時:【値例】2025/01/01 00:00:00");

                    b.HasKey("Id")
                        .HasName("m_affiliate_user_PKC");

                    b.ToTable("m_affiliate_user", t =>
                        {
                            t.HasComment("アフィリエイトユーザマスタ");
                        });
                });

            modelBuilder.Entity("DMMAffiDBEntity.Entities.Transaction.TProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigserial")
                        .HasColumnName("id")
                        .HasComment("商品ID:【値例】1");

                    b.Property<string>("CreateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("create_program")
                        .HasComment("作成プログラム:【値例】System");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("create_user")
                        .HasComment("作成者:【値例】System");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasComment("作成日時:【値例】2025/01/01 00:00:00");

                    b.Property<JsonDocument>("ProductContent")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("product_content")
                        .HasComment("商品内容:【値例】");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("update_program")
                        .HasComment("更新プログラム:【値例】System");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("update_user")
                        .HasComment("更新者:【値例】System");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date")
                        .HasComment("更新日時:【値例】2025/01/01 00:00:00");

                    b.HasKey("Id")
                        .HasName("t_product_PKC");

                    b.ToTable("t_product", t =>
                        {
                            t.HasComment("商品テーブル");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
